FROM amazoncorretto:21 AS builder

WORKDIR /app
COPY backend-spring/. /app
RUN ./gradlew bootJar --no-daemon

FROM amazoncorretto:21

WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]